workflows:
  ios-testflight:
    name: iOS TestFlight
    max_build_duration: 60
    instance_type: mac_mini_m2

    integrations:
      app_store_connect: Codemagic

    environment:
      flutter: stable
      xcode: latest
      cocoapods: default
      ios_signing:
        distribution_type: app_store
        bundle_identifier: br.com.aeternalegado.app

    scripts:
      - name: Get Flutter packages
        script: |
          flutter pub get

      - name: Set up iOS code signing
        script: |
          keychain initialize
          app-store-connect fetch-signing-files br.com.aeternalegado.app --type IOS_APP_STORE --create
          keychain add-certificates

      - name: Build IPA
        script: |
          flutter build ipa --release --export-options-plist=$HOME/export_options.plist

    artifacts:
      - build/ios/ipa/*.ipa

    publishing:
      app_store_connect:
        auth: integration
        submit_to_testflight: true
